### ISSUE TITLE
Let "enter" on login page trigger "log in" button

### ISSUE THREAD

**Issue by ronichoudhury** [XDATA-Year-2/sitar#10]

**Comment by ronichoudhury** [comment]
This would take listening to the ``keydown`` event on the password or username field, so is not a standard behavior.  No need for it in Sitar, especially you can tab over to the button and then hit enter.

**Comment by jeffbaumes** [comment]
I'd recommend looking into this a bit more. It is fairly standard that hitting enter on a form text field submits the form - I think browsers generally do this when there is a `<form>` with an action. You could figure out the proper `<form>` semantics and use that - looks like the jQuery `submit` function is what you would want, with `preventDefault`:

http://api.jquery.com/submit/

or bind directly to the enter key (I have done this - seems to work fine but is less clean):

http://stackoverflow.com/questions/979662/how-to-detect-pressing-enter-on-keyboard-using-jquery

Also would be curious how Girder handles this, since there are many forms in that UI.

**Comment by ronichoudhury** [comment]
Wrapping the text fields and buttons in a ``<form>`` element worked nicely - I just had to change the target element from the button to the form, the name of the event from "click" to "submit", and I had to add a ``preventDefault()`` to the end of the callback to prevent the page from reloading.
